"""Creation of tables

Revision ID: 3c3c282765e6
Revises: 
Create Date: 2025-08-30 08:27:13.157496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3c282765e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('word', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('definitions', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('translations', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('ADJECTIVE', 'ADJECTIVE_NUMERAL', 'ADJECTIVE_NOUN', 'ADJECTIVE_PRONOUN', 'ADJECTIVE_NOUN_ALT', 'ADVERB', 'ADVERB_NEGATIVE_MARKER', 'ADVERB_NOUN', 'INDEFINITE_ARTICLE', 'CONJUNCTION', 'CONJUNCTION_SUBORDINATE_NEXUS', 'SUBORDINATE_CONJUNCTION', 'EXPRESSION', 'IDIOMATIC_EXPRESSION', 'TEMPORAL_EXPRESSION', 'PHRASE', 'HABITUAL_IMPERFECT', 'IMPERATIVE_PLURAL', 'IMPERATIVE_SINGULAR', 'PERIPHRASTIC_IMPERFECT', 'SIMPLE_IMPERFECT_SUFFIX', 'INTERJECTION', 'LOCUTION', 'ADVERBIAL_LOCUTION', 'ASPECTUAL_MARKER', 'ASPECTUAL_MARKER_IMPERFECT', 'EXISTENCE_MARKER', 'PRAGMATIC_MARKER', 'PREVERBAL_ASPECTUAL_TEMPORAL_MARKER', 'TEMPORAL_ASPECTUAL_MARKER', 'TEMPORAL_ASPECTUAL_MARKER_ALT', 'VERBAL_MARKER', 'VERBAL_ASPECTUAL_MARKER', 'NEGATIVE_NULL', 'SUBORDINATE_NEXUS', 'NUMBER', 'PARTICIPLE', 'PREPOSITION', 'PREPOSITION_SUBORDINATE_NEXUS', 'SPANISH_BORROWING', 'PRONOUN', 'PRONOUN_PLURAL_ARTICLE', 'PRONOUN_SUBORDINATE_CONJUNCTION', 'PRONOUN_INTERROGATIVE', 'PRONOUN_PREPOSITION_VERB', 'DEMONSTRATIVE_PRONOUN', 'INDEFINITE_PRONOUN', 'PERSONAL_PRONOUN', 'PERSONAL_PRONOUN_ALT', 'ENCLITIC_PERSONAL_PRONOUN', 'RELATIVE_PRONOUN', 'SUFFIX', 'NOUN', 'NOUN_ADJECTIVE', 'NOUN_DEROGATORY', 'COLLECTIVE_NOUN', 'MASCULINE_FEMININE_NOUN', 'PLURAL_NOUN', 'PROPER_NOUN', 'NOUN_ADJECTIVE_ALT', 'TITLE', 'ATONIC_VARIANT', 'VERB', 'VERB_NOUN', 'COPULATIVE_VERB', 'COPULATIVE_VERB_PRETERITE', 'COPULATIVE_VERB_VARIANT', 'IMPERFECT_COPULATIVE_VERB', 'PRESENT_COPULATIVE_VERB', 'IMPERSONAL_VERB', 'INFINITIVE_VERB', 'INFINITIVE_VERB_TEMPORAL_MARKER', 'INFINITIVE_VERB_COPULATIVE_VERB', 'INTRANSITIVE_VERB', 'IMPERFECT_MODAL_VERB', 'PRONOMINAL_VERB', 'REFLEXIVE_VERB', 'TRANSITIVE_VERB', 'NONE', name='wordtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_id'), 'word', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_id'), table_name='word')
    op.drop_table('word')
    # ### end Alembic commands ###
