import sqlmodel

"""Added cover column to articles

Revision ID: 8c9faa65e4de
Revises: f49b9452b2c6
Create Date: 2026-03-14 17:53:30.016584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9faa65e4de'
down_revision: Union[str, Sequence[str], None] = 'f49b9452b2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'cover')
    # ### end Alembic commands ###
