"""Added created_by and updated_by columns to word model

Revision ID: 9a703740f6e2
Revises: 241536997bdf
Create Date: 2025-09-03 22:41:58.484764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a703740f6e2'
down_revision: Union[str, Sequence[str], None] = '241536997bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('word', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'word', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'word', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_column('word', 'updated_by')
    op.drop_column('word', 'created_by')
    # ### end Alembic commands ###
