"""Add examples column to the word model

Revision ID: f49b9452b2c6
Revises: 7b2bf755796a
Create Date: 2025-09-09 22:41:07.692297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49b9452b2c6'
down_revision: Union[str, Sequence[str], None] = '7b2bf755796a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('examples', sa.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'examples')
    # ### end Alembic commands ###
